Hw07 file copying
ivfisunov/otus_hw pull request #11
Opened 2020-10-30 14:45 UTC by ivfisunov

## Домашнее задание №7 «Утилита для копирования файлов»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-10-31 13:40 UTC, agneum requested changes
Хорошая работа. Не хватает только тестов.
Итого: 6 баллов из 10.

2020-10-31 13:40 UTC, agneum commented on hw07_file_copying/copy.go
> +	}
Если требуется при создании выставить права на файл, можно сделать одним вызовом функции https://golang.org/pkg/os/#OpenFile

2020-10-31 13:40 UTC, agneum commented on hw07_file_copying/copy.go
> +			return errors.New("error writing file")
Здесь можно обернуть ошибку, добавив дополнительную информацию о ней: https://blog.golang.org/go1.13-errors (`Wrapping errors with %w`)
Либо воспользоваться сторонним пакетом https://github.com/pkg/errors

2020-10-31 19:14 UTC, ivfisunov commented
@agneum Артем, тесты добавил, прошу допроверить
спасибо

2020-10-31 19:19 UTC, ivfisunov commented on hw07_file_copying/copy.go
> +	}
@agneum не нашел простого способа установить права точно такие же как у копируемого файла, функция Mode() возвращает строку "rwx...", а OpenFile принимает восьмиричное число

2020-11-01 12:18 UTC, agneum commented on hw07_file_copying/copy_test.go
> +		err := Copy("testdata/input.txt", "testdata/out_offset0_limit10.txt", 0, 10)
Предлагаю в тестах при работе с файлами, особенно при удалении, использовать функции
https://golang.org/pkg/io/ioutil/#TempDir и
https://golang.org/pkg/io/ioutil/#TempFile

2020-11-01 12:19 UTC, agneum approved these changes
Спасибо за выполненное задание
Итого: 9 баллов из 10.

2020-11-07 10:16 UTC, merged