hw11 done
ivfisunov/otus_hw pull request #15
Opened 2020-12-08 15:03 UTC by ivfisunov

## Домашнее задание №11 «Клиент TELNET»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 4 баллов

#### Зачёт от 7 баллов

2020-12-11 06:52 UTC, balabanovds requested changes
Работа неплохая, но есть замечания
Одно из основных - клиент не закрывается чисто при нажатии `ctrl+d`, а продолжает читать
```
...EOF
error: read tcp [::1]:49904->[::1]:4242: use of closed network connection
```
Также есть незначительные замечания по коду

https://otus.ru/teacher-lk/homework/144932/8092/

2020-12-11 06:52 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	client := NewTelnetClient(host+":"+port, timeout, os.Stdin, os.Stdout)
есть `net.JoinHostPort`

2020-12-11 06:52 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	client.Close()
а почему закрываете только на Send? если у Вас закрывает соединение удаленный сервер, разве не нужно клиента закрывать?

2020-12-11 06:52 UTC, balabanovds commented on hw11_telnet_client/telnet.go
> +		return fmt.Errorf("%w", err)
зачем оборачивать без доп инфы? тогда уж просто вернуть ошибку

2020-12-11 06:52 UTC, balabanovds commented on hw11_telnet_client/main.go
> +func Receive(client TelnetClient, wg *sync.WaitGroup) {
Зачем экспортировать функцию? Это ведь бинарь, а не либа

2020-12-11 19:31 UTC, ivfisunov commented on hw11_telnet_client/telnet.go
> +		return fmt.Errorf("%w", err)
@balabanovds линтер ругается что надо обернуть если просто возвращать

2020-12-12 17:42 UTC, balabanovds requested changes
Видно что исправили незначительные замечания, но основное осталось.
Подумайте еще, где нужно закрывать клиента.
Если будут вопросы, доступен в Slack

Успехов!

2020-12-12 17:42 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	defer client.Close()
Вы в двух горутинах закрываете client. Если в одном закрыли, то в другом может выскочить nil pointer или еще что-то

2020-12-14 16:27 UTC, balabanovds reviewed
Вы уже близки к решению! =)

Если есть вопросы, то можно связаться в Slack.

2020-12-14 16:27 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	eofCh := make(chan string, 1)
предлагаю подумать над подходом - как-то сказать всем дочерним горутинам, что если проблема возникнет в одной из горутин, то мы об этом узнаем в основной горутине и предпримем именно в основной горутине определенные шаги.

2020-12-15 15:48 UTC, balabanovds requested changes
Уже лучше, но все равно нужно доделать

Попробуйте решить с помощью контекста, ведь это была одна из тем перед ДЗ.
Просто можно сильно упростить Ваш код - перенесите select в конец основной горутины, тогда и необходимость в WaitGroup отпадет.

2020-12-15 15:48 UTC, balabanovds commented on hw11_telnet_client/main.go
> +				os.Exit(-1)
здесь если прилетит сигнал от os Вы жестко закрываете, клиент также жестко дропается

2020-12-15 15:48 UTC, balabanovds commented on hw11_telnet_client/main.go
> +				client.Close()
достаточно вынести client.Close() в defer, так Вы упрощаете код
defer обычно располагается рядом с инициацией

2020-12-15 15:48 UTC, balabanovds commented on hw11_telnet_client/main.go
> +		for {
зачем тут for?

2020-12-15 15:48 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	go func() {
можно и в основной горутине если переместить в конец

2020-12-16 05:29 UTC, balabanovds requested changes
Хорошая  работа! 
Есть несколько замечаний, на которые хотелось бы обратить Ваше внимание.

2020-12-16 05:29 UTC, balabanovds commented on hw11_telnet_client/main.go
> +		return
return тут не нужен, Вы находитесь в основной горутине

2020-12-16 08:21 UTC, balabanovds approved these changes
Хорошая работа!

8/10

2020-12-16 08:21 UTC, balabanovds commented on hw11_telnet_client/main.go
> +
defer close()

2020-12-27 12:33 UTC, merged